### ISSUE TITLE
[Site] Mobile Menu not clickable

### ISSUE THREAD

**Issue by tonyzeoli** [netmix/radio-station-pro#37]
**Describe the bug**

The mobile menu in Netmix.com is not working correctly. 

**To Reproduce**
1. Go to Netmix.com on a mobile device
2. Click on Menu
3. Nothing happens

**Expected behavior**

Menu is supposed to drop down.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Pleae check why there is extra space above the menu, as well. Looks like the utility nav links are missing.

**Comment by majick777** [comment]
I haven't been able to reproduce this, seems to work fine now. Checked in a few browsers and on my mobile. I'd say it was probably the jQuery loading conflict bug that was causing this to happen. 

Can you confirm with whatever browser/device you were experiencing the problem with? If it is still happening for you the other possibility is that it is browser specific and I can test further.

**Comment by tonyzeoli** [comment]
Tested this in Chrome for iPhone and is working fine now. Thanks for fixing.
